### ISSUE TITLE
Which port does the frontend connect to?

### ISSUE THREAD

**Issue by dheeraj-chakilam** [jihchi/reason-react-realworld-example-app#1]
I've been trying to get this running using an fsharp backend. However, it seems like my backend never receives a connection.

Can the host be something like `host = "http://127.0.0.1:8080/";`?

**Comment by jihchi** [comment]
Yes, It should be able to point to `http://127.0.0.1` as your backend.

Please try to change the code over ere:
https://github.com/jihchi/reason-react-realworld-example-app/blob/2e775f70505c325ef9b3a77be896e148f98c68f0/src/API.re#L3

Replace `https://conduit.productionready.io` by `http://127.0.0.1:8080`, then make sure you have re-compiled `API.re`.

```diff
-let host = "https://conduit.productionready.io";
+let host = "http://127.0.0.1:8080";
```

After you got the latest bundle code and refresh the webpage, you should be able to see the network request in `DevTools > Network Panel` (assuming you're using Chrome):
![screenshot_2019-04-17 19-51-06](https://user-images.githubusercontent.com/87983/56285591-2b185580-614a-11e9-90c4-f542fce3cb07.jpg)

**Comment by dheeraj-chakilam** [comment]
I think the issue is with fsharp backend. For example the fsharp backend doesn't use `path` in the request URLs. Perhaps it's using an older version of the API?
