### ISSUE TITLE
The Login page can't redirect home page after fulfilling user info and click login button

### ISSUE THREAD

**Issue by HeathKang** [jihchi/reason-react-realworld-example-app#24]
Description
----------------
The `Login` page can't redirect `Home` page after fulfilling user info and clicking `login` button

Root Cause
---------------
There is no `id`, `createdAt`, `updatedAt` field in the response JSON, so raises error according to `Option.getExn` method.
![image](https://user-images.githubusercontent.com/16971300/196725907-08707c77-1047-4cdd-9e9b-4acd30d413c3.png)

**Comment by HeathKang** [comment]
If anyone who also encountered this problem is interested. Here is a workaround commit, it works for me.
![image](https://user-images.githubusercontent.com/16971300/196727869-8e617c47-fd9d-489b-a01d-7d09478e8cf1.png)

https://github.com/HeathKang/rescript-react-realworld-example-app/commit/0e5580942fe1ec472bd2b8b7cf604739a673ff07

**Comment by jihchi** [comment]
Thank you for the report!

It seems that both `POST https://api.realworld.io/api/users` and `POST https://api.realworld.io/api/users/login` has introduced a breaking-change in the response.

I've removed the missing fields in #25.
